"""

Revision ID: 14dd19fe8428
Revises: 1fe6859ab703
Create Date: 2025-05-14 05:16:12.221406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14dd19fe8428'
down_revision: Union[str, None] = '1fe6859ab703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('campaign_name', sa.String(), nullable=False))
    op.drop_constraint('unique_workspace_campaign_name', 'campaigns', type_='unique')
    op.create_unique_constraint('unique_workspace_campaign_name', 'campaigns', ['workspace_id', 'campaign_name'])
    op.drop_column('campaigns', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('unique_workspace_campaign_name', 'campaigns', type_='unique')
    op.create_unique_constraint('unique_workspace_campaign_name', 'campaigns', ['workspace_id', 'name'])
    op.drop_column('campaigns', 'campaign_name')
    # ### end Alembic commands ###
