"""

Revision ID: 1fe6859ab703
Revises: 671b75fb57ad
Create Date: 2025-05-14 05:14:50.768977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fe6859ab703'
down_revision: Union[str, None] = '671b75fb57ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('target_audience', postgresql.ARRAY(sa.String()), nullable=False))
    op.drop_column('campaigns', 'target_audiences')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('target_audiences', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_column('campaigns', 'target_audience')
    # ### end Alembic commands ###
