"""

Revision ID: 208c227626b0
Revises: d8794fb611f0
Create Date: 2025-05-22 23:02:40.123479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '208c227626b0'
down_revision: Union[str, None] = 'd8794fb611f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('signup_price_tag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'signup_price_tag')
    # ### end Alembic commands ###
