"""

Revision ID: 2bc7553007f0
Revises: 208c227626b0
Create Date: 2025-05-26 03:10:01.738608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2bc7553007f0'
down_revision: Union[str, None] = '208c227626b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('telegram_chat_ids', postgresql.ARRAY(sa.String()), nullable=False, server_default="{}"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_posts', 'is_published')
    op.drop_column('campaigns', 'telegram_chat_ids')
    # ### end Alembic commands ###
