"""

Revision ID: 3dd44be7d2b8
Revises: d374a1548737
Create Date: 2025-05-19 23:29:01.179795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dd44be7d2b8'
down_revision: Union[str, None] = 'd374a1548737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_settings', sa.Column('persona', sa.String(), nullable=False, server_default="neutral"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_settings', 'persona')
    # ### end Alembic commands ###
