"""

Revision ID: 4b7c267ca76a
Revises: 8e208845e214
Create Date: 2025-05-17 10:50:57.538801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b7c267ca76a'
down_revision: Union[str, None] = '8e208845e214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_workspace_campaign_platform', 'platform_connections', type_='unique')
    op.create_unique_constraint('unique_workspace_campaign_platform_nonce', 'platform_connections', ['workspace_id', 'campaign_id', 'platform', 'nonce'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_workspace_campaign_platform_nonce', 'platform_connections', type_='unique')
    op.create_unique_constraint('unique_workspace_campaign_platform', 'platform_connections', ['workspace_id', 'campaign_id', 'platform'])
    # ### end Alembic commands ###
