"""

Revision ID: 635bbe196125
Revises: 6d855190b3e5
Create Date: 2025-05-18 23:34:23.028617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '635bbe196125'
down_revision: Union[str, None] = '6d855190b3e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('managed_telegram_bot_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'campaigns', 'managed_telegram_bots', ['managed_telegram_bot_id'], ['id'])
    op.add_column('managed_telegram_bots', sa.Column('max_campaigns', sa.Integer(), nullable=False, server_default='50'))
    op.add_column('managed_telegram_bots', sa.Column('is_exclusive', sa.Boolean(), nullable=False, server_default='False'))
    op.drop_constraint('managed_telegram_bots_assigned_workspace_id_fkey', 'managed_telegram_bots', type_='foreignkey')
    op.drop_constraint('managed_telegram_bots_assigned_campaign_id_fkey', 'managed_telegram_bots', type_='foreignkey')
    op.drop_column('managed_telegram_bots', 'is_available')
    op.drop_column('managed_telegram_bots', 'assigned')
    op.drop_column('managed_telegram_bots', 'assigned_campaign_id')
    op.drop_column('managed_telegram_bots', 'assigned_workspace_id')
    op.drop_column('managed_telegram_bots', 'is_connected')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managed_telegram_bots', sa.Column('is_connected', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('managed_telegram_bots', sa.Column('assigned_workspace_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('managed_telegram_bots', sa.Column('assigned_campaign_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('managed_telegram_bots', sa.Column('assigned', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('managed_telegram_bots', sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_foreign_key('managed_telegram_bots_assigned_campaign_id_fkey', 'managed_telegram_bots',
                          'campaigns', ['assigned_campaign_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('managed_telegram_bots_assigned_workspace_id_fkey', 'managed_telegram_bots',
                          'workspaces', ['assigned_workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_column('managed_telegram_bots', 'is_exclusive')
    op.drop_column('managed_telegram_bots', 'max_campaigns')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_column('campaigns', 'managed_telegram_bot_id')
    # ### end Alembic commands ###
