"""

Revision ID: 67515ed10299
Revises: 8c3c50294384
Create Date: 2025-05-16 06:29:02.707727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67515ed10299'
down_revision: Union[str, None] = '8c3c50294384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_connections', sa.Column('campaign_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('unique_workspace_campaign_platform', 'platform_connections', ['workspace_id', 'campaign_id', 'platform'])
    op.create_foreign_key(None, 'platform_connections', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'platform_connections', type_='foreignkey')
    op.drop_constraint('unique_workspace_campaign_platform', 'platform_connections', type_='unique')
    op.drop_column('platform_connections', 'campaign_id')
    # ### end Alembic commands ###
