"""

Revision ID: 6d855190b3e5
Revises: ef40c2a25ac6
Create Date: 2025-05-18 22:55:20.103036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d855190b3e5'
down_revision: Union[str, None] = 'ef40c2a25ac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('managed_telegram_bots', 'bot_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('managed_telegram_bots', 'bot_photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managed_telegram_bots', sa.Column('bot_photo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('managed_telegram_bots', 'bot_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
