"""

Revision ID: 8e208845e214
Revises: 67515ed10299
Create Date: 2025-05-17 10:49:04.034396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e208845e214'
down_revision: Union[str, None] = '67515ed10299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_connections', sa.Column('nonce', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_connections', 'nonce')
    # ### end Alembic commands ###
