"""

Revision ID: 9f4807c2d82f
Revises: 4b7c267ca76a
Create Date: 2025-05-17 11:37:52.513067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f4807c2d82f'
down_revision: Union[str, None] = '4b7c267ca76a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_connections', sa.Column('scope', sa.String(), nullable=False,))
    op.add_column('platform_connections', sa.Column('redirect_uri', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_connections', 'redirect_uri')
    op.drop_column('platform_connections', 'scope')
    # ### end Alembic commands ###
