"""

Revision ID: a92fbe8fddb9
Revises: 2e27def95af3
Create Date: 2025-05-11 16:43:31.387015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a92fbe8fddb9'
down_revision: Union[str, None] = '2e27def95af3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('campaign_type', sa.String(), nullable=False),
    sa.Column('target_platforms', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('engagement_style', sa.String(), nullable=False),
    sa.Column('target_audiences', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('campaign_start_date', sa.DateTime(), nullable=False),
    sa.Column('campaign_timeline', sa.String(), nullable=False),
    sa.Column('project_info', sa.String(), nullable=False),
    sa.Column('project_website', sa.String(), nullable=True),
    sa.Column('project_twitter', sa.String(), nullable=True),
    sa.Column('project_telegram', sa.String(), nullable=True),
    sa.Column('project_discord', sa.String(), nullable=True),
    sa.Column('project_logo', sa.String(), nullable=True),
    sa.Column('project_banner', sa.String(), nullable=True),
    sa.Column('project_whitepaper', sa.String(), nullable=True),
    sa.Column('project_token_address', sa.String(), nullable=True),
    sa.Column('project_token_symbol', sa.String(), nullable=True),
    sa.Column('project_token_decimals', sa.Integer(), nullable=True),
    sa.Column('project_token_supply', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='unique_workspace_campaign_name')
    )
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
