"""

Revision ID: be491a6b3210
Revises: 791c3d745b84
Create Date: 2025-05-15 15:43:08.620547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be491a6b3210'
down_revision: Union[str, None] = '791c3d745b84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_settings', 'plagiarism_check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_settings', sa.Column('plagiarism_check', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
