"""

Revision ID: ea20c040c837
Revises: 3dd44be7d2b8
Create Date: 2025-05-20 08:32:47.414749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea20c040c837'
down_revision: Union[str, None] = '3dd44be7d2b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_settings', sa.Column('origin_timezone', sa.String(), nullable=False, server_default="UTC"))
    op.add_column('campaign_settings', sa.Column('origin_continent', sa.String(), nullable=False, server_default="NA"))
    op.add_column('campaign_settings', sa.Column('primary_language', sa.String(), nullable=False, server_default="en"))
    op.add_column('campaign_settings', sa.Column('date_format', sa.String(), nullable=False, server_default="MM/DD/YYYY"))
    op.add_column('campaign_settings', sa.Column('time_format', sa.String(), nullable=False, server_default="HH:MM"))
    op.add_column('campaign_settings', sa.Column('holiday_awareness', sa.Boolean(), nullable=False, server_default='False'))
    op.add_column('campaigns', sa.Column('is_system_campaign', sa.Boolean(), nullable=False, server_default='False'))
    op.add_column('campaigns', sa.Column('last_run_at', sa.DateTime(), nullable=True))
    op.add_column('campaigns', sa.Column('next_run_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'next_run_at')
    op.drop_column('campaigns', 'last_run_at')
    op.drop_column('campaigns', 'is_system_campaign')
    op.drop_column('campaign_settings', 'holiday_awareness')
    op.drop_column('campaign_settings', 'time_format')
    op.drop_column('campaign_settings', 'date_format')
    op.drop_column('campaign_settings', 'primary_language')
    op.drop_column('campaign_settings', 'origin_continent')
    op.drop_column('campaign_settings', 'origin_timezone')
    # ### end Alembic commands ###
