"""

Revision ID: ef40c2a25ac6
Revises: 9f4807c2d82f
Create Date: 2025-05-18 22:49:15.858334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef40c2a25ac6'
down_revision: Union[str, None] = '9f4807c2d82f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managed_telegram_bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_token', sa.String(), nullable=False),
    sa.Column('bot_username', sa.String(), nullable=False),
    sa.Column('bot_name', sa.String(), nullable=False),
    sa.Column('bot_description', sa.String(), nullable=False),
    sa.Column('bot_photo', sa.String(), nullable=True),
    sa.Column('bot_photo_url', sa.String(), nullable=True),
    sa.Column('assigned', sa.Boolean(), nullable=False),
    sa.Column('assigned_campaign_id', sa.Integer(), nullable=True),
    sa.Column('assigned_workspace_id', sa.Integer(), nullable=True),
    sa.Column('last_assigned_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('requires_token_refresh', sa.Boolean(), nullable=False),
    sa.Column('token_refresh_required_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_token', 'bot_username', name='unique_bot_token_username')
    )
    op.create_index(op.f('ix_managed_telegram_bots_id'), 'managed_telegram_bots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_managed_telegram_bots_id'), table_name='managed_telegram_bots')
    op.drop_table('managed_telegram_bots')
    # ### end Alembic commands ###
